apiVersion: v1
kind: Service
metadata:
  name: backend # this becomes the DNS name: http://backend:8000
spec:
  selector:
    app: backend # routes to pods with this label
  ports:
    - protocol: TCP
      port: 8000 # port the Service listens on (inside cluster)
      targetPort: 8000 # port on the pod to forward to
  type: NodePort # Change to LoadBalancer if on cloud, or use Ingress for more control

---
apiVersion: v1
kind: Service
metadata:
  name: frontend # this becomes the DNS name: http://frontend:8000
spec:
  selector:
    app: frontend # routes to pods with this label
  ports:
    - protocol: TCP
      port: 3000 # port the Service listens on (inside cluster)
      targetPort: 3000 # port on the pod to forward to
  type: NodePort # Change to LoadBalancer if on cloud, or use Ingress for more control
